package oxcmail

import (
	"bytes"
	stdmime "mime"
	"mime/multipart"
	"mime/quotedprintable"
	"net/mail"
	"net/textproto"
	"strings"

	"hermex/internal/mapi"
)

// dateLayout is the RFC 5322 date format Export synthesizes (the wire form of
// strftime "%a, %d %b %Y %H:%M:%S %z").
const dateLayout = "Mon, 02 Jan 2006 15:04:05 -0700"

// Export renders a MAPI Message into a wire-format RFC 5322 / MIME message,
// implementing the MS-OXCMAIL MAPI-to-internet export path. It synthesizes fresh
// headers, MIME structure, and transfer encodings; it does not reproduce any
// original bytes (the Date and the chosen encodings are generated afresh, so the
// output is a valid message but not byte-identical to what was imported).
//
// The core path emits a single text/plain body; multipart bodies
// (alternative/mixed/related) and HTML are widened in a later slice. opt is
// currently unused (the core property set carries no named properties).
func Export(msg *Message, opt Options) ([]byte, error) {
	var b bytes.Buffer
	writeMailHead(&b, msg)
	if err := writeBody(&b, msg); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// writeBody appends the body section, choosing the skeleton from the body
// properties: multipart/alternative when both plain and HTML are present,
// text/html when only HTML, text/plain otherwise.
func writeBody(b *bytes.Buffer, msg *Message) error {
	plain := propString(msg.Props, mapi.PrBody)
	html, hasHTML := bytesProp(msg.Props, mapi.PrHTML)
	switch {
	case hasHTML && plain != "":
		return writeAlternativeBody(b, plain, html, htmlCharset(msg.Props))
	case hasHTML:
		writeHTMLBody(b, html, htmlCharset(msg.Props))
	default:
		writeTextBody(b, plain)
	}
	return nil
}

// writeAlternativeBody emits a multipart/alternative body with a text/plain and
// a text/html part. The boundary is generated by the multipart writer.
func writeAlternativeBody(b *bytes.Buffer, plain string, html []byte, htmlCset string) error {
	var parts bytes.Buffer
	mw := multipart.NewWriter(&parts)

	pcte, penc := encodeForTransfer([]byte(plain))
	ph := textproto.MIMEHeader{}
	ph.Set("Content-Type", "text/plain; charset=utf-8")
	ph.Set("Content-Transfer-Encoding", pcte)
	pw, err := mw.CreatePart(ph)
	if err != nil {
		return err
	}
	pw.Write(penc)

	hcte, henc := encodeForTransfer(html)
	hh := textproto.MIMEHeader{}
	hh.Set("Content-Type", "text/html; charset="+htmlCset)
	hh.Set("Content-Transfer-Encoding", hcte)
	hw, err := mw.CreatePart(hh)
	if err != nil {
		return err
	}
	hw.Write(henc)

	if err := mw.Close(); err != nil {
		return err
	}
	writeField(b, "Content-Type", "multipart/alternative; boundary=\""+mw.Boundary()+"\"")
	b.WriteString("\r\n")
	b.Write(parts.Bytes())
	return nil
}

// writeHTMLBody emits a single text/html body in its stored charset.
func writeHTMLBody(b *bytes.Buffer, html []byte, charset string) {
	cte, enc := encodeForTransfer(html)
	writeField(b, "Content-Type", "text/html; charset="+charset)
	writeField(b, "Content-Transfer-Encoding", cte)
	b.WriteString("\r\n")
	b.Write(enc)
}

// writeMailHead synthesizes the message header block (no trailing blank line;
// the body writer appends the content headers and the separator), following the
// header order of the MS-OXCMAIL export path.
func writeMailHead(b *bytes.Buffer, msg *Message) {
	writeField(b, "MIME-Version", "1.0")

	// From carries the sent-representing identity.
	if from := identityAddress(msg.Props, representingTags); from != "" {
		writeField(b, "From", from)
	}
	// Sender is emitted only when it differs from the representing address.
	senderSMTP := propString(msg.Props, mapi.PrSenderSmtpAddress)
	reprSMTP := propString(msg.Props, mapi.PrSentRepresentingSmtpAddress)
	if senderSMTP != "" && !strings.EqualFold(senderSMTP, reprSMTP) {
		if s := identityAddress(msg.Props, senderTags); s != "" {
			writeField(b, "Sender", s)
		}
	}

	if to := recipientList(msg, mapi.RecipTo); to != "" {
		writeField(b, "To", to)
	}
	if cc := recipientList(msg, mapi.RecipCc); cc != "" {
		writeField(b, "Cc", cc)
	}
	if bcc := recipientList(msg, mapi.RecipBcc); bcc != "" {
		writeField(b, "Bcc", bcc)
	}

	if v, ok := propInt32(msg.Props, mapi.PrImportance); ok {
		writeField(b, "Importance", importanceText(v))
	}
	if v, ok := propInt32(msg.Props, mapi.PrSensitivity); ok {
		writeField(b, "Sensitivity", sensitivityText(v))
	}

	if v, ok := propUint64(msg.Props, mapi.PrClientSubmitTime); ok {
		writeField(b, "Date", mapi.NTTimeToUnix(v).UTC().Format(dateLayout))
	}

	writeField(b, "Subject", encodeText(subjectText(msg.Props)))

	if topic := propString(msg.Props, mapi.PrConversationTopic); topic != "" {
		writeField(b, "Thread-Topic", encodeText(topic))
	}
	if id := propString(msg.Props, mapi.PrInternetMessageID); id != "" {
		writeField(b, "Message-ID", id)
	}
	if refs := propString(msg.Props, mapi.PrInternetReferences); refs != "" {
		writeField(b, "References", refs)
	}
	if irt := propString(msg.Props, mapi.PrInReplyToID); irt != "" {
		writeField(b, "In-Reply-To", irt)
	}
}

// writeTextBody appends the content headers, the header/body separator, and the
// transfer-encoded text/plain body.
func writeTextBody(b *bytes.Buffer, body string) {
	cte, enc := encodeForTransfer([]byte(body))
	writeField(b, "Content-Type", "text/plain; charset=utf-8")
	writeField(b, "Content-Transfer-Encoding", cte)
	b.WriteString("\r\n")
	b.Write(enc)
}

// encodeForTransfer picks a content-transfer-encoding for raw and returns the
// encoding name and the encoded bytes: 7bit when the content is 7-bit-clean,
// quoted-printable otherwise.
func encodeForTransfer(raw []byte) (string, []byte) {
	if is7bitClean(raw) {
		return "7bit", raw
	}
	var buf bytes.Buffer
	w := quotedprintable.NewWriter(&buf)
	w.Write(raw)
	w.Close()
	return "quoted-printable", buf.Bytes()
}

// htmlCharset returns the charset name for the HTML body from PR_INTERNET_CPID,
// defaulting to UTF-8.
func htmlCharset(props mapi.PropertyValues) string {
	if v, ok := propInt32(props, mapi.PrInternetCodepage); ok {
		return cpidToCset(v)
	}
	return "utf-8"
}

// bytesProp returns a []byte-typed property and whether it was present.
func bytesProp(props mapi.PropertyValues, tag mapi.PropTag) ([]byte, bool) {
	if v, ok := props.Get(tag); ok {
		if b, ok := v.([]byte); ok {
			return b, true
		}
	}
	return nil, false
}

// identityAddress formats one identity (sender or sent-representing) as an
// address-list element ("Name <addr>"), or "" when no address is present.
func identityAddress(props mapi.PropertyValues, t addrTags) string {
	addr := propString(props, t.smtp)
	if addr == "" {
		addr = propString(props, t.email)
	}
	if addr == "" {
		return ""
	}
	a := mail.Address{Name: propString(props, t.name), Address: addr}
	return a.String()
}

// recipientList formats all recipients of one type as a comma-separated address
// list, or "" when there are none.
func recipientList(msg *Message, rcptType int32) string {
	var addrs []string
	for _, r := range msg.Recipients {
		if v, ok := propInt32(r, mapi.PrRecipientType); !ok || v != rcptType {
			continue
		}
		addr := propString(r, mapi.PrSmtpAddress)
		if addr == "" {
			addr = propString(r, mapi.PrEmailAddress)
		}
		if addr == "" {
			continue
		}
		a := mail.Address{Name: propString(r, mapi.PrDisplayName), Address: addr}
		addrs = append(addrs, a.String())
	}
	return strings.Join(addrs, ", ")
}

// subjectText reconstructs the Subject from the prefix and normalized subject
// (both are set on import), falling back to PR_SUBJECT.
func subjectText(props mapi.PropertyValues) string {
	prefix, hasPrefix := props.Get(mapi.PrSubjectPrefix)
	normalized, hasNorm := props.Get(mapi.PrNormalizedSubject)
	if hasPrefix && hasNorm {
		p, _ := prefix.(string)
		n, _ := normalized.(string)
		return p + n
	}
	return propString(props, mapi.PrSubject)
}

// importanceText maps PR_IMPORTANCE to its header value (always emitted).
func importanceText(v int32) string {
	switch v {
	case mapi.ImportanceLow:
		return "Low"
	case mapi.ImportanceHigh:
		return "High"
	}
	return "Normal"
}

// sensitivityText maps PR_SENSITIVITY to its header value (always emitted).
func sensitivityText(v int32) string {
	switch v {
	case mapi.SensitivityPersonal:
		return "Personal"
	case mapi.SensitivityPrivate:
		return "Private"
	case mapi.SensitivityConfidential:
		return "Company-Confidential"
	}
	return "Normal"
}

// encodeText returns the RFC 2047 encoded-word form of s when it contains
// non-ASCII or control characters, and s unchanged otherwise.
func encodeText(s string) string {
	return stdmime.QEncoding.Encode("utf-8", s)
}

// is7bitClean reports whether b is safe to emit as 7bit: only printable ASCII
// plus tab, CR, and LF.
func is7bitClean(b []byte) bool {
	for i := 0; i < len(b); i++ {
		c := b[i]
		if c == '\t' || c == '\r' || c == '\n' {
			continue
		}
		if c < 0x20 || c > 0x7E {
			return false
		}
	}
	return true
}

// writeField writes one "Name: value" header line, CRLF-terminated.
func writeField(b *bytes.Buffer, name, value string) {
	b.WriteString(name)
	b.WriteString(": ")
	b.WriteString(value)
	b.WriteString("\r\n")
}

// propString returns a string-typed property, or "" when absent or not a string.
func propString(props mapi.PropertyValues, tag mapi.PropTag) string {
	if v, ok := props.Get(tag); ok {
		if s, ok := v.(string); ok {
			return s
		}
	}
	return ""
}

// propInt32 returns an int32-typed property and whether it was present.
func propInt32(props mapi.PropertyValues, tag mapi.PropTag) (int32, bool) {
	if v, ok := props.Get(tag); ok {
		if n, ok := v.(int32); ok {
			return n, true
		}
	}
	return 0, false
}

// propUint64 returns a uint64-typed property and whether it was present.
func propUint64(props mapi.PropertyValues, tag mapi.PropTag) (uint64, bool) {
	if v, ok := props.Get(tag); ok {
		if n, ok := v.(uint64); ok {
			return n, true
		}
	}
	return 0, false
}
