package rop

import (
	"strings"
	"testing"

	"hermex/internal/directory"
	"hermex/internal/mapi"
	"hermex/internal/objectstore"
	"hermex/internal/oxcmail"
)

// seedReceiptRequest writes an unread Inbox message that requested a read receipt,
// with the represented sender set to sender, and returns its stored id. It mirrors
// a message imported from mail carrying a Disposition-Notification-To header.
func seedReceiptRequest(t *testing.T, dir, sender, subject string) int64 {
	t.Helper()
	st, err := objectstore.Open(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer st.Close()
	id, err := st.CreateMessage(int64(mapi.PrivateFIDInbox), &oxcmail.Message{
		Props: mapi.PropertyValues{
			{Tag: mapi.PrMessageClass, Value: "IPM.Note"},
			{Tag: mapi.PrSubject, Value: subject},
			{Tag: mapi.PrInternetMessageID, Value: "<orig-1@hermex.test>"},
			{Tag: mapi.PrReadReceiptRequested, Value: true},
			{Tag: mapi.PrNonReceiptNotificationRequested, Value: true},
			{Tag: mapi.PrSentRepresentingSmtpAddress, Value: sender},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	return id
}

// markReadDirect flips a message's read state through the store, bypassing the ROP
// handler — standing in for a read performed over another protocol (IMAP \Seen),
// which leaves PR_READ_RECEIPT_REQUESTED untouched.
func markReadDirect(t *testing.T, dir string, msgID int64) {
	t.Helper()
	st, err := objectstore.Open(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer st.Close()
	if err := st.SetMessageReadState(msgID, true); err != nil {
		t.Fatal(err)
	}
}

// receiptRequested reports whether a message still carries PR_READ_RECEIPT_REQUESTED.
func receiptRequested(t *testing.T, dir string, msgID int64) bool {
	t.Helper()
	st, err := objectstore.Open(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer st.Close()
	props, err := st.GetMessageProperties(msgID, mapi.PrReadReceiptRequested)
	if err != nil {
		t.Fatal(err)
	}
	v, _ := props.Get(mapi.PrReadReceiptRequested)
	b, _ := v.(bool)
	return b
}

// readReceiptSession seeds a reader mailbox holding one receipt-requesting message
// from sender, and opens a ROP session + message handle ready for SetMessageReadFlag.
// Both reader and sender are local so a generated receipt lands in the sender's inbox.
func readReceiptSession(t *testing.T) (sess *Session, logonH, msgH uint32, msgID int64, readerDir, senderDir string) {
	t.Helper()
	readerDir, senderDir = t.TempDir(), t.TempDir()
	accounts := directory.StaticAccounts{
		"reader@hermex.test": {MailboxPath: readerDir},
		"sender@hermex.test": {MailboxPath: senderDir},
	}
	msgID = seedReceiptRequest(t, readerDir, "sender@hermex.test", "PingMe")
	inboxEID := uint64(mapi.MakeEIDEx(1, mapi.PrivateFIDInbox))
	msgEID := uint64(mapi.MakeEIDEx(1, uint64(msgID)))

	sess = NewSession(readerDir, accounts, "reader@hermex.test")
	_, h := sess.Dispatch(logonRequest(0, 0x01), []uint32{0xFFFFFFFF})
	logonH = h[0]
	_, h = sess.Dispatch(buildOpenMessage(0, 1, inboxEID, msgEID), []uint32{logonH, 0xFFFFFFFF})
	msgH = h[1]
	return
}

// TestReadReceiptGeneratedOnFirstRead drives the end-to-end trigger path: marking
// an unread, receipt-requesting message read (rfDefault) delivers exactly one read
// notification to the represented sender and consumes the request flag. It asserts
// what the ROP trigger owns — delivery to the sender, the read-notification
// identity, the disposition data, and the flag-clear. The full multipart/report
// MDN wire structure is asserted on the generated bytes in the mta package; local
// delivery round-trips through oxcmail, which does not model report/MDN MIME, so
// the stored copy is not the place to check the wire shape.
func TestReadReceiptGeneratedOnFirstRead(t *testing.T) {
	sess, logonH, msgH, msgID, readerDir, senderDir := readReceiptSession(t)
	defer sess.Close()

	sess.Dispatch(buildSetMessageReadFlag(0, 1, rfDefault), []uint32{logonH, msgH})

	if n := inboxCount(t, senderDir); n != 1 {
		t.Fatalf("sender inbox = %d after first read, want 1 read receipt", n)
	}
	raw := string(firstInboxRaw(t, senderDir))
	if !strings.Contains(raw, "Your message has been read!") {
		t.Errorf("delivered message is not the read notification:\n%s", raw)
	}
	if !strings.Contains(raw, "displayed") {
		t.Errorf("delivered receipt missing the read disposition:\n%s", raw)
	}
	if !strings.Contains(raw, "reader@hermex.test") {
		t.Errorf("delivered receipt not from the reader:\n%s", raw)
	}
	if receiptRequested(t, readerDir, msgID) {
		t.Errorf("PR_READ_RECEIPT_REQUESTED still set after sending; the receipt would re-fire")
	}
}

// TestReadReceiptFiresOnceViaFlagClear isolates the flag-clear once-guard: after
// the first receipt, marking the message unread again and re-reading must NOT
// produce a second receipt — even though the unread→read transition recurs — because
// the request flag was consumed on the first send.
func TestReadReceiptFiresOnceViaFlagClear(t *testing.T) {
	sess, logonH, msgH, _, _, senderDir := readReceiptSession(t)
	defer sess.Close()

	sess.Dispatch(buildSetMessageReadFlag(0, 1, rfDefault), []uint32{logonH, msgH})
	if n := inboxCount(t, senderDir); n != 1 {
		t.Fatalf("sender inbox = %d after first read, want 1", n)
	}
	// Re-create the unread→read transition; the flag-clear must still block a resend.
	sess.Dispatch(buildSetMessageReadFlag(0, 1, rfClearReadFlag), []uint32{logonH, msgH})
	sess.Dispatch(buildSetMessageReadFlag(0, 1, rfDefault), []uint32{logonH, msgH})
	if n := inboxCount(t, senderDir); n != 1 {
		t.Errorf("sender inbox = %d after re-read, want still 1 (fire-once via flag clear)", n)
	}
}

// TestReadReceiptTransitionGate is the gate's teeth: a message already marked read
// through another protocol (here, directly through the store, as IMAP \Seen would)
// must NOT fire a receipt when an Outlook client subsequently opens it with
// rfDefault — there is no unread→read transition. A flag-only guard would fire a
// spurious receipt here.
func TestReadReceiptTransitionGate(t *testing.T) {
	readerDir, senderDir := t.TempDir(), t.TempDir()
	accounts := directory.StaticAccounts{
		"reader@hermex.test": {MailboxPath: readerDir},
		"sender@hermex.test": {MailboxPath: senderDir},
	}
	msgID := seedReceiptRequest(t, readerDir, "sender@hermex.test", "PingMe")
	markReadDirect(t, readerDir, msgID) // IMAP \Seen: read, but request flag intact

	inboxEID := uint64(mapi.MakeEIDEx(1, mapi.PrivateFIDInbox))
	msgEID := uint64(mapi.MakeEIDEx(1, uint64(msgID)))
	sess := NewSession(readerDir, accounts, "reader@hermex.test")
	defer sess.Close()
	_, h := sess.Dispatch(logonRequest(0, 0x01), []uint32{0xFFFFFFFF})
	logonH := h[0]
	_, h = sess.Dispatch(buildOpenMessage(0, 1, inboxEID, msgEID), []uint32{logonH, 0xFFFFFFFF})
	msgH := h[1]

	sess.Dispatch(buildSetMessageReadFlag(0, 1, rfDefault), []uint32{logonH, msgH})
	if n := inboxCount(t, senderDir); n != 0 {
		t.Errorf("sender inbox = %d, want 0 (no transition → no receipt)", n)
	}
}

// TestReadReceiptSuppressed pins rfSuppressReceipt: the message is marked read but
// NO receipt is sent and the request flag is preserved (a later unsuppressed read
// can still produce it). A "clear whenever read" simplification would wrongly
// consume the request here.
func TestReadReceiptSuppressed(t *testing.T) {
	sess, logonH, msgH, msgID, readerDir, senderDir := readReceiptSession(t)
	defer sess.Close()

	sess.Dispatch(buildSetMessageReadFlag(0, 1, rfSuppressReceipt), []uint32{logonH, msgH})

	if n := inboxCount(t, senderDir); n != 0 {
		t.Errorf("sender inbox = %d after suppressed read, want 0", n)
	}
	if !receiptRequested(t, readerDir, msgID) {
		t.Errorf("PR_READ_RECEIPT_REQUESTED cleared by a suppressed read; the request must survive")
	}
}
