package crypt

import (
	"strings"
	"testing"
)

// The vectors below were produced by OpenSSL's own crypt(3) implementation
// (openssl passwd -6 / -1), an implementation with no code in common with this
// one. They are what makes this package's output verifiable rather than merely
// self-consistent: a stored password is only useful if every other crypt(3)
// implementation agrees on what it hashes to.
var sha512Vectors = []struct{ name, salt, password, want string }{
	{
		"the specification's own example",
		"saltstring", "Hello world!",
		"$6$saltstring$svn8UoSVapNtMuq1ukKS4tPQd8iKwSMHWjl/O817G3uBnIFNjnQJuesI68u4OTLiBFdcbYEdFCoEOfaS35inz1",
	},
	{
		"a full 16-character salt, the length this package generates",
		"YMHsHVYtVGpe3sHz", "correct horse battery staple",
		"$6$YMHsHVYtVGpe3sHz$xyhx.KBpq1C4zkavTwvY6BeSPUXvne/tmfIydBhaiT8gJj9en.WwSJja9pbFVebU1GRF0wPzsrAalxeqM5sVN.",
	},
	{
		"a two-character salt",
		"ab", "short salt",
		"$6$ab$rkMmYTSRxKYBHHm7EfUNl0RmRzR9DsZuuebjDnqzRHTGIrpNKUySqH7UstnePAGpT.4NMHJ7PhCKNmGKxcnPf0",
	},
}

// TestSHA512MatchesAnIndependentImplementation is the core correctness proof: the
// derivation and the permuted hash64 output both have to agree with crypt(3) to
// the byte, or every password this directory stores becomes unverifiable
// anywhere else.
func TestSHA512MatchesAnIndependentImplementation(t *testing.T) {
	for _, tc := range sha512Vectors {
		t.Run(tc.name, func(t *testing.T) {
			got := formatSHA512(tc.salt, SHA512RoundsDefault, false, sha512Crypt([]byte(tc.password), []byte(tc.salt), SHA512RoundsDefault))
			if got != tc.want {
				t.Errorf("hash = %q\nwant  %q", got, tc.want)
			}
			if !Verify(tc.password, tc.want) {
				t.Error("Verify rejected the password that made this hash")
			}
			if Verify(tc.password+"x", tc.want) {
				t.Error("Verify accepted a wrong password")
			}
		})
	}
}

// TestMD5MatchesAnIndependentImplementation covers the scheme kept for
// interoperability. The first vector is Poul-Henning Kamp's canonical one, which
// OpenSSL reproduces byte for byte.
func TestMD5MatchesAnIndependentImplementation(t *testing.T) {
	for _, tc := range []struct{ salt, password, want string }{
		{"saltstri", "Hello world!", "$1$saltstri$YMyguxXMBpd2TEZ.vS/3q1"},
		{"abcd1234", "p@ssw0rd", "$1$abcd1234$fnzJaF8HRJIVA/1c2IUOG1"},
	} {
		got := MD5Prefix + tc.salt + "$" + string(md5Crypt([]byte(tc.password), []byte(tc.salt)))
		if got != tc.want {
			t.Errorf("hash = %q\nwant  %q", got, tc.want)
		}
		if !Verify(tc.password, tc.want) || Verify("wrong", tc.want) {
			t.Errorf("Verify did not match exactly the password behind %q", tc.want)
		}
	}
}

// TestStoredHashesFromTheOldLibraryStillVerify is the upgrade guarantee. These
// two hashes were generated by the third-party library this package replaced,
// one at the work factor the directory uses and one at the scheme default, so
// they stand for every password already in a deployed database.
func TestStoredHashesFromTheOldLibraryStillVerify(t *testing.T) {
	for _, tc := range []struct{ password, stored string }{
		{
			"correct horse battery staple",
			"$6$rounds=600000$IjGRcu8H2WQ6E6y3$Gz8.jIWFdIHaMrofUtBng//z0slfchDgSHQCWhDPOio8yILjEFDnjY3C810TGXvm/aT9aD3/SQZV.3avmRbns.",
		},
		{
			"Hello world!",
			"$6$VUlmZ7sjBAIJ6NSf$lVyWacsv4X1O173UlVU5mQ5IFMnFGfvci7cKeihR6Ge.kapGq/pw0SzbnUaHk829JjUzt5Myi0CvDoOUtVdv4.",
		},
	} {
		if !Verify(tc.password, tc.stored) {
			t.Errorf("a hash stored by the previous implementation no longer verifies: %q", tc.stored)
		}
		if Verify("wrong password", tc.stored) {
			t.Errorf("a stored hash verified a wrong password: %q", tc.stored)
		}
	}
}

// TestNewSHA512RoundTrips proves a freshly generated hash carries its work
// factor, uses a full salt, and matches exactly its own password.
func TestNewSHA512RoundTrips(t *testing.T) {
	h, err := NewSHA512("s3cret", 1000)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(h, "$6$rounds=1000$") {
		t.Errorf("hash = %q, want an explicit rounds section", h)
	}
	salt, rounds, explicit, ok := parseSHA512(h)
	if !ok || !explicit || rounds != 1000 || len(salt) != sha512SaltLenMax {
		t.Errorf("parsed salt=%q rounds=%d explicit=%v ok=%v", salt, rounds, explicit, ok)
	}
	if !Verify("s3cret", h) || Verify("s3cre", h) {
		t.Error("the fresh hash did not match exactly its own password")
	}

	// At the scheme default the rounds section is omitted, which is what makes a
	// hash comparable with one written by any other crypt(3).
	def, err := NewSHA512("s3cret", SHA512RoundsDefault)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(def, "rounds=") {
		t.Errorf("hash at the scheme default = %q, want no rounds section", def)
	}
	if !Verify("s3cret", def) {
		t.Error("the default-factor hash does not verify")
	}
}

// TestTwoHashesOfOnePasswordDiffer proves the salt is actually random, so a
// leaked database cannot be attacked by grouping identical hashes.
func TestTwoHashesOfOnePasswordDiffer(t *testing.T) {
	a, err := NewSHA512("same password", 1000)
	if err != nil {
		t.Fatal(err)
	}
	b, err := NewSHA512("same password", 1000)
	if err != nil {
		t.Fatal(err)
	}
	if a == b {
		t.Error("two hashes of one password are identical, so the salt is not random")
	}
}

// TestRoundsReadsStoredHashes pins the parser the re-hash decision rests on.
func TestRoundsReadsStoredHashes(t *testing.T) {
	for _, tc := range []struct {
		name, stored string
		want         int
		wantOK       bool
	}{
		{"explicit rounds", "$6$rounds=600000$salt$hash", 600000, true},
		{"no rounds section", "$6$salt$hash", SHA512RoundsDefault, true},
		{"below the minimum is clamped up", "$6$rounds=1$salt$hash", SHA512RoundsMin, true},
		{"md5-crypt has no comparable factor", "$1$salt$hash", 0, false},
		{"empty", "", 0, false},
		{"unparseable rounds", "$6$rounds=abc$salt$hash", 0, false},
		{"truncated rounds section", "$6$rounds=600000", 0, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, ok := Rounds(tc.stored)
			if got != tc.want || ok != tc.wantOK {
				t.Errorf("Rounds(%q) = (%d, %v), want (%d, %v)", tc.stored, got, ok, tc.want, tc.wantOK)
			}
		})
	}
}

// TestVerifyRejectsWhatItDoesNotUnderstand proves an unknown or empty stored
// value never matches, rather than falling through to some default.
func TestVerifyRejectsWhatItDoesNotUnderstand(t *testing.T) {
	for _, stored := range []string{
		"", "plaintext", "$2y$10$unsupportedbcrypthashvalue", "$5$salt$sha256crypt", "$6$", "$1$",
	} {
		if Verify("x", stored) || Verify("", stored) {
			t.Errorf("an unsupported stored value matched: %q", stored)
		}
	}
}

// TestSaltLimitsMatchTheSchemes proves each scheme's salt limit is applied when a
// stored hash is read. crypt(3) never writes a longer salt field than this, so a
// value that carries one is malformed and must not be silently hashed in full:
// the limit decides what the derivation actually sees.
func TestSaltLimitsMatchTheSchemes(t *testing.T) {
	salt, _, _, ok := parseSHA512("$6$0123456789abcdefGHIJK$digest")
	if !ok || salt != "0123456789abcdef" {
		t.Errorf("sha512 salt = %q (ok=%v), want the first %d characters", salt, ok, sha512SaltLenMax)
	}
	md5Salt, ok := parseMD5("$1$0123456789$digest")
	if !ok || md5Salt != "01234567" {
		t.Errorf("md5 salt = %q (ok=%v), want the first %d characters", md5Salt, ok, md5SaltLenMax)
	}
	// The salt beyond the limit really does change the derivation, so truncating
	// at the right place is what keeps a stored hash verifiable.
	full := sha512Crypt([]byte("pw"), []byte("0123456789abcdefGHIJK"), SHA512RoundsDefault)
	cut := sha512Crypt([]byte("pw"), []byte("0123456789abcdef"), SHA512RoundsDefault)
	if string(full) == string(cut) {
		t.Error("the derivation ignores the extra salt on its own, so the limit is untested")
	}
}
